name: .NET Core

on: [push]

jobs:
  build:
    strategy:
      matrix:
        dotnet: [ '5.0.100-rc.2.20479.15' ]
        os: [windows-latest]
        
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.dotnet }}
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - name: Getting context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Getting code
      uses: actions/checkout@v1
          
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
        includePrerelease: true
    
    - name: Build
      run: dotnet build src --configuration Release --nologo
    
    - name: Run tests
      run: dotnet test src --configuration Release --nologo
      
    - name: Try Publish(if the version has changed)
      if: runner.os == 'Windows' &&
          matrix.dotnet == '5.0.100-rc.2.20479.15'
      run: dotnet nuget push src\NotifyIconWpf\bin\Release\Hardcodet.NotifyIcon.Wpf.NetCore.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json; exit 0
