name: .NET
on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        dotnet: [ '5.x' ]
        os: [ windows-latest ]
        
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.dotnet }}
    env:
      DOTNET_NOLOGO: true
    
    steps:
    - name: Getting code
      uses: actions/checkout@v1
          
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Build
      run: dotnet build src --configuration Release --nologo
      
    - name: Try Publish
      run: dotnet nuget push src\NotifyIconWpf\bin\Release\Hardcodet.NotifyIcon.Wpf.NetCore.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json; exit 0
