name: Build, test and publish
on: [ push ]

jobs:
  build-test-publish:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      os: windows-2022
      use-msbuild: true
      project-path: 
        /target:libs\H_NotifyIcon_Uno
        /target:libs\H_NotifyIcon_Uno_WinUI
        /target:libs\H_NotifyIcon_WinUI
        /target:libs\H_NotifyIcon_Wpf
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
